# Generated by Django 4.2.3 on 2023-08-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlists',
            options={'verbose_name_plural': 'Wishlists'},
        ),
    ]
